export const travelPackages = [
  {
    id: 1,
    name: "Eksplorasi Bali & Nusa Penida",
    price: "Rp 3.500.000",
    priceNumeric: 3500000,
    location: "Bali, Indonesia",
    category: "Alam & Budaya",
    duration: "4 Hari 3 Malam",
    rating: 4.9,
    reviewCount: 128,
    updatedAt: "2026-03-05",
    image:
      "https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=800&q=80",
    description:
      "Nikmati keindahan Pulau Dewata dengan mengunjungi Pura Ulun Danu Beratan, tebing spektakuler Uluwatu, hingga keajaiban bawah laut Nusa Penida. Paket ini mencakup tur budaya, snorkeling, dan menikmati sunset terbaik di Bali.",
    highlights: [
      "Snorkeling di Nusa Penida",
      "Pura Tanah Lot",
      "Tegallalang Rice Terrace",
      "Seminyak Beach",
    ],
    included: [
      "Hotel Bintang 4",
      "Transportasi AC",
      "Makan 3x Sehari",
      "Tiket Wisata",
      "Tour Guide",
      "Asuransi",
    ],
  },
  {
    id: 2,
    name: "Petualangan Raja Ampat",
    price: "Rp 8.200.000",
    priceNumeric: 8200000,
    location: "Papua, Indonesia",
    category: "Bahari",
    duration: "6 Hari 5 Malam",
    rating: 4.8,
    reviewCount: 74,
    updatedAt: "2026-03-04",
    image:
      "https://images.unsplash.com/photo-1516690561799-46d8f74f9abf?auto=format&fit=crop&w=800&q=80",
    description:
      "Raja Ampat adalah surga bagi para penyelam dan pecinta alam laut. Dengan lebih dari 1.500 spesies ikan dan 75% spesies karang dunia, kawasan ini menawarkan pengalaman menyelam dan snorkeling tanpa tandingan di dunia.",
    highlights: [
      "Diving di Wayag",
      "Pulau Pianemo",
      "Snorkeling Manta Ray",
      "Sunset di Puncak Arborek",
    ],
    included: [
      "Homestay Premium",
      "Speedboat",
      "Makan 3x Sehari",
      "Peralatan Snorkeling",
      "Tour Guide",
      "Asuransi",
    ],
  },
  {
    id: 3,
    name: "Pesona Danau Toba",
    price: "Rp 2.800.000",
    priceNumeric: 2800000,
    location: "Sumatera Utara, Indonesia",
    category: "Budaya",
    duration: "3 Hari 2 Malam",
    rating: 4.7,
    reviewCount: 95,
    updatedAt: "2026-03-02",
    image:
      "https://images.unsplash.com/photo-1724909627713-866347d7d00e?q=80&w=1331&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description:
      "Danau Toba adalah kaldera vulkanik terbesar di dunia dan rumah bagi budaya Batak yang kaya. Jelajahi Pulau Samosir, rasakan keramahan penduduk lokal, dan nikmati pemandangan danau yang memukau dari berbagai sudut.",
    highlights: ["Pulau Samosir", "Desa Adat Tomok", "Museum Batak", "Air Terjun Situmorang"],
    included: [
      "Penginapan Tepi Danau",
      "Transportasi",
      "Makan 3x Sehari",
      "Tiket Wisata",
      "Tour Guide",
      "Asuransi",
    ],
  },
  {
    id: 4,
    name: "Liburan Musim Dingin Jepang",
    price: "Rp 21.000.000",
    priceNumeric: 21000000,
    location: "Tokyo & Kyoto, Jepang",
    category: "Internasional",
    duration: "8 Hari 7 Malam",
    rating: 5.0,
    reviewCount: 53,
    updatedAt: "2026-03-06",
    image:
      "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=800&q=80",
    description:
      "Rasakan sihir musim dingin Jepang dengan salju di Gunung Fuji, festival cahaya Illumination, dan ketenangan kuil-kuil bersejarah Kyoto yang tertutup salju. Pengalaman Jepang yang paling romantis dan tak terlupakan.",
    highlights: [
      "Gunung Fuji & Hakone",
      "Fushimi Inari Kyoto",
      "Shibuya & Shinjuku Tokyo",
      "Nishiki Market",
    ],
    included: [
      "Hotel Bintang 4",
      "Tiket JR Pass",
      "Makan 2x Sehari",
      "Tiket Wisata",
      "Tour Guide",
      "Asuransi",
    ],
  },
  {
    id: 5,
    name: "Romantisme Maldives",
    price: "Rp 35.000.000",
    priceNumeric: 35000000,
    location: "Male, Maldives",
    category: "Honeymoon",
    duration: "5 Hari 4 Malam",
    rating: 5.0,
    reviewCount: 41,
    updatedAt: "2026-03-03",
    image:
      "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=800&q=80",
    description:
      "Maldives menawarkan pengalaman overwater bungalow ikonik dengan air laut sebiru kristal. Ideal untuk bulan madu atau liburan romantis — menikmati matahari terbenam di atas lautan, diving bersama hiu paus, dan dinner di tepi pantai.",
    highlights: [
      "Overwater Villa",
      "Diving Bersama Pari Manta",
      "Sunset Cruise",
      "Private Beach Dinner",
    ],
    included: [
      "Villa Overwater",
      "Speedboat Transfer",
      "All Inclusive",
      "Peralatan Snorkeling",
      "Butler Service",
      "Asuransi",
    ],
  },
  {
    id: 6,
    name: "Safari di Kawah Ijen",
    price: "Rp 1.500.000",
    priceNumeric: 1500000,
    location: "Banyuwangi, Indonesia",
    category: "Petualangan",
    duration: "2 Hari 1 Malam",
    rating: 4.6,
    reviewCount: 187,
    updatedAt: "2026-03-01",
    image:
      "https://images.unsplash.com/photo-1575242385452-44b445d98f34?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description:
      "Kawah Ijen terkenal dengan fenomena blue fire yang hanya ada dua di dunia. Pendakian dini hari untuk menyaksikan api biru misterius dan danau asam terhijau di dunia menjadi pengalaman yang akan dikenang seumur hidup.",
    highlights: [
      "Blue Fire Kawah Ijen",
      "Sunrise di Puncak",
      "Pantai Pulau Merah",
      "Desa Osing Kemiren",
    ],
    included: [
      "Penginapan Lokal",
      "Transportasi",
      "Makan 2x Sehari",
      "Masker Gas",
      "Porter",
      "Asuransi",
    ],
  },
];

export const categories = [
  { id: "all", label: "Semua" },
  { id: "Alam & Budaya", label: "Alam & Budaya" },
  { id: "Bahari", label: "Bahari" },
  { id: "Budaya", label: "Budaya" },
  { id: "Internasional", label: "Internasional" },
  { id: "Honeymoon", label: "Honeymoon" },
  { id: "Petualangan", label: "Petualangan" },
];

export const testimonials = [
  {
    id: 1,
    name: "Rina Susanti",
    location: "Jakarta",
    packageName: "Eksplorasi Bali & Nusa Penida",
    rating: 5,
    avatar:
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=100&q=80",
    text: "Pengalaman terbaik dalam hidup saya! Tour guide sangat profesional, penginapannya nyaman, dan itinerary sudah dipikirkan dengan matang. Pasti akan booking lagi!",
  },
  {
    id: 2,
    name: "Budi Santoso",
    location: "Surabaya",
    packageName: "Petualangan Raja Ampat",
    rating: 5,
    avatar:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=100&q=80",
    text: "Raja Ampat melampaui semua ekspektasi saya. Tim Travelista mengurus semuanya dengan sempurna — dari penerbangan, homestay, hingga diving equipment. Highly recommended!",
  },
  {
    id: 3,
    name: "Sari Dewi",
    location: "Bandung",
    packageName: "Romantisme Maldives",
    rating: 5,
    avatar:
      "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=100&q=80",
    text: "Bulan madu kami di Maldives sungguh sempurna berkat Travelista. Detail-detail kecil seperti dekorasi kamar dan private dinner sudah disiapkan dengan sangat baik. Terima kasih!",
  },
  {
    id: 4,
    name: "Dimas Pratama",
    location: "Medan",
    packageName: "Liburan Musim Dingin Jepang",
    rating: 5,
    avatar:
      "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=100&q=80",
    text: "Jepang di musim dingin benar-benar magis. Travelista memilih destinasi dan waktu yang tepat. JR Pass sangat memudahkan mobilitas. Tidak ada satupun momen yang mengecewakan.",
  },
];
